// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

TestCase := Rectangle {
    a := Arc {
        stroke: #ff0000;
        stroke-width: 5px;
        start-angle: 45deg;
        end-angle: 180deg;
        stroke-line-cap: LineCap.round;
    }

    out property<bool> test:
        a.stroke == #ff0000 &&
        a.stroke-width == 5px &&
        a.start-angle == 45deg &&
        a.end-angle == 180deg &&
        a.stroke-line-cap == LineCap.round;
}

/*
```rust
let instance = TestCase::new().unwrap();
assert!(instance.get_test());
```
*/
